volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    expose:
      - "8000"
    ports:
    - "8000:8000"
    volumes:
      - static:/app/collected_static 
      - media:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/ && tail -f /dev/null
    volumes:
      - static:/frontend_static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - static:/app/collected_static 
      - media:/app/media
      - static:/frontend_static
    depends_on:
      - backend
      - frontend
