# Generated by Django 5.2.6 on 2025-10-05 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_follow_author_alter_follow_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Обязательное поле",
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Разрешены только буквы, цифры и символы @/./+/-/_",
                        regex="^[\\w.@+-]+\\Z",
                    )
                ],
                verbose_name="Имя пользователя",
            ),
        ),
    ]
